import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "D&D Check Logger",
  description: "Generated by create next app",
  creator:"Pedro Braga Magalhães",
  keywords: ["d&d","react","tailwind", "ability", "skill", "check", "log"]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " px-10 sm:py-4"}>{children}</body>
    </html>
  );
}
